"""Generate startup files for frozen and embedded applications."""

import argparse
import os
import sys

TYPE_CHECKING = False

if TYPE_CHECKING:
    from os import PathLike
    from typing import Literal

    _FrozenIntegration = Literal["cx-freeze", "embedded", "nuitka", "pyinstaller"]

_INTEGRATIONS = ("cx-freeze", "embedded", "nuitka", "pyinstaller")
_HEADER = "# Generated by metapathology; safe to check into an application."


def render(
    integration: "_FrozenIntegration",
    *,
    module: str | None = None,
    entry_point: str = "main",
) -> str:
    """Render deterministic source for one supported startup integration.

    Args:
        integration: Supported freezer or embedding integration.
        module: Application module dispatched by the Nuitka launcher.
        entry_point: Callable imported from the Nuitka application module.

    Returns:
        Complete generated Python source.

    Raises:
        ValueError: If the integration is unknown or its arguments are invalid.
    """
    if integration not in _INTEGRATIONS:
        raise ValueError(f"unsupported frozen integration: {integration!r}")
    if integration == "nuitka" and not module:
        raise ValueError("the nuitka integration requires an application module")
    if integration != "nuitka" and module is not None:
        raise ValueError("an application module is only valid for the nuitka integration")
    if integration != "nuitka" and entry_point != "main":
        raise ValueError("an application entry point is only valid for the nuitka integration")
    if module is not None and (
        any(not part.isidentifier() for part in module.split(".")) or not entry_point.isidentifier()
    ):
        raise ValueError("Nuitka module and entry point names must be valid dotted Python identifiers")
    source = (
        f"{_HEADER}\n"
        "try:\n"
        "    from metapathology._frozen_bootstrap import activate_frozen as _metapathology_activate\n"
        f"    _metapathology_activate({integration!r}, __file__)\n"
        "except Exception as _metapathology_error:\n"
        "    try:\n"
        "        import sys as _metapathology_sys\n"
        "        _metapathology_sys.stderr.write(\n"
        "            'metapathology frozen bootstrap: activation failed: '\n"
        "            + type(_metapathology_error).__name__\n"
        "            + ': '\n"
        "            + str(_metapathology_error)[:200]\n"
        "            + '\\n'\n"
        "        )\n"
        "    except Exception:\n"
        "        pass\n"
    )
    if module is not None:
        source += f"\nfrom {module} import {entry_point} as _metapathology_entry_point\n_metapathology_entry_point()\n"
    elif integration == "cx-freeze":
        source += (
            "\n"
            "import importlib.util as _metapathology_importlib_util\n"
            "import sys as _metapathology_sys\n"
            "_metapathology_sys.frozen = True\n"
            "\n"
            "def run(name):\n"
            "    spec = _metapathology_importlib_util.find_spec(name)\n"
            "    code = spec.loader.get_code(name)\n"
            "    main_globals = _metapathology_sys.modules['__main__'].__dict__\n"
            "    main_globals.update(\n"
            "        __cached__=spec.cached,\n"
            "        __file__=spec.cached,\n"
            "        __loader__=spec.loader,\n"
            "        __spec__=spec,\n"
            "    )\n"
            "    exec(code, main_globals)\n"
        )
    return source


def generate(
    integration: "_FrozenIntegration",
    output: "str | PathLike[str]",
    *,
    module: str | None = None,
    entry_point: str = "main",
    force: bool = False,
) -> str:
    """Write one generated startup file without silently replacing user data.

    Args:
        integration: Supported freezer or embedding integration.
        output: Destination Python file.
        module: Application module dispatched by the Nuitka launcher.
        entry_point: Callable imported from the Nuitka application module.
        force: Replace an existing regular file when true.

    Returns:
        Absolute destination path.

    Raises:
        FileExistsError: If the destination exists and ``force`` is false.
        OSError: If the destination cannot be inspected or written.
        TypeError: If the destination resolves to bytes.
        ValueError: If generation arguments are inconsistent.
    """
    raw_output = os.fspath(output)
    if not isinstance(raw_output, str):
        raise TypeError("bootstrap paths must resolve to str, not bytes")
    path = os.path.abspath(raw_output)
    source = render(integration, module=module, entry_point=entry_point)
    mode = "w" if force and os.path.isfile(path) and not os.path.islink(path) else "x"
    with open(path, mode, encoding="utf-8", newline="\n") as stream:
        stream.write(source)
    return path


class _Arguments(argparse.Namespace):
    """Typed generator command destinations."""

    def __init__(self) -> None:
        super().__init__()
        self.command = ""
        self.integration = ""
        self.output = ""
        self.module: str | None = None
        self.entry_point = "main"
        self.force = False


def _parser() -> argparse.ArgumentParser:
    """Build the standalone generator CLI."""
    parser = argparse.ArgumentParser(
        prog="python -m metapathology.frozen_bootstrap",
        description="Generate a metapathology startup file for a frozen or embedded application.",
    )
    commands = parser.add_subparsers(dest="command", required=True)
    generate_parser = commands.add_parser("generate")
    generate_parser.add_argument("integration", choices=_INTEGRATIONS)
    generate_parser.add_argument("output", metavar="OUTPUT.py")
    generate_parser.add_argument("--module", help="application module for the Nuitka entry launcher")
    generate_parser.add_argument("--callable", dest="entry_point", default="main", help="Nuitka module callable")
    generate_parser.add_argument("--force", action="store_true", help="replace an existing regular file")
    return parser


def main(argv: list[str] | None = None) -> int:
    """Run the generator CLI and return its process status."""
    arguments = _Arguments()
    _parser().parse_args(argv, namespace=arguments)
    try:
        integration = arguments.integration
        if integration not in _INTEGRATIONS:
            raise ValueError(f"unsupported frozen integration: {integration!r}")
        path = generate(
            integration,
            arguments.output,
            module=arguments.module,
            entry_point=arguments.entry_point,
            force=arguments.force,
        )  # type: ignore[arg-type]
    except (OSError, TypeError, ValueError) as exc:
        sys.stderr.write(f"metapathology frozen bootstrap: {exc}\n")
        return 1
    sys.stdout.write(f"generated: {path}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
